In [2]:
import pandas as pd

## Analisando Dados de Account

account_account_account =pd.read_json('base_dados/accounts/01-accounts-accounts.json')
account_details = pd.read_json('base_dados/accounts/02-accounts-details.json')
account_balances = pd.read_json('base_dados/accounts/03-accounts-balances.json')
account_transactions = pd.read_json('base_dados/accounts/04-accounts-transactions.json')
accounts_overdraft_limits = pd.read_json('base_dados/accounts/05-accounts-overdraft-limits.json')

In [28]:

account_account_account.to_csv('account.csv',sep = ';', index=False)

In [29]:
account_details.to_csv('account_details.csv',sep = ';', index=False)

In [30]:
account_balances.to_csv('balances.csv',sep = ';' , index=False)

In [31]:
account_transactions.to_csv('transactions.csv',sep = ';', index=False)

In [32]:
accounts_overdraft_limits.to_csv('overdraft_limits.csv',sep = ';', index=False)

### Análisando Dados de  credit-cards

In [42]:
credit_cards =pd.read_json('base_dados/credit-cards/01-credit-cards.json')
credit_cards_details = pd.read_json('base_dados/credit-cards/02-credit-cards-details.json')
credit_cards_limit = pd.read_json('base_dados/credit-cards/03-credit-cards-limits.json')
credit_cards_transactions = pd.read_json('base_dados/credit-cards/04-credit-cards-transactions.json')
credit_cards_bills = pd.read_json('base_dados/credit-cards/05-credit-cards-bills.json')
credit_cards_bills_transaction = pd.read_json('base_dados/credit-cards/06-credit-cards-bills-transactions.json')

In [43]:
credit_cards.to_csv('credit-cards.csv',sep = ';', index=False)
credit_cards_details.to_csv('credit_cards_details.csv',sep = ';', index=False)
credit_cards_limit.to_csv('credit_cards_limit.csv',sep = ';', index=False)
credit_cards_transactions.to_csv('credit_cards_transactions.csv',sep = ';', index=False)
credit_cards_bills.to_csv('credit_cards_bills.csv',sep = ';', index=False)
credit_cards_bills_transaction.to_csv('credit_cards_bills_transaction.csv',sep = ';', index=False)

In [45]:
credit_cards_bills_transaction.head()

,creditCardAccountId,customerId,organizationId,organizationName,transactionId,identificationNumber,transactionName,creditDebitType,transactionType,paymentType,feeType,chargeIdentificator,chargeNumber,brazilianAmount,amount,currency,transactionDate,billPostDate,payeeMCC,billId
0,e1711229-cf83-483b-8cc1-0c8d31c81f80,362.529.240-03,63d929c5-2a09-479e-806c-8cd073a029ab,Instituição Financeira 05,193a5bb2-9e69-4266-abd0-f20ab4540e32,3876,Decoração,DEBITO,PAGAMENTO,A_VISTA,ANUIDADE,NaN,NaN,836.55,836.55,BRL,2021-07-30,2021-08-10,NaN,fdf99beb-f235-43f2-a410-d8d279dcfd0f
1,e1711229-cf83-483b-8cc1-0c8d31c81f80,362.529.240-03,63d929c5-2a09-479e-806c-8cd073a029ab,Instituição Financeira 05,d5a68784-c8ad-4f1a-834b-945509f11499,3876,Telefone,DEBITO,PAGAMENTO,A_VISTA,ANUIDADE,NaN,NaN,216.94,216.94,BRL,2021-07-06,2021-08-10,NaN,fdf99beb-f235-43f2-a410-d8d279dcfd0f
2,e1711229-cf83-483b-8cc1-0c8d31c81f80,362.529.240-03,63d929c5-2a09-479e-806c-8cd073a029ab,Instituição Financeira 05,6037e5c4-6e4a-48ae-ab19-fc225bbbbe23,3876,Transporte,DEBITO,PAGAMENTO,A_VISTA,ANUIDADE,NaN,NaN,8853.08,8853.08,BRL,2021-07-20,2021-08-10,NaN,fdf99beb-f235-43f2-a410-d8d279dcfd0f
3,e1711229-cf83-483b-8cc1-0c8d31c81f80,362.529.240-03,63d929c5-2a09-479e-806c-8cd073a029ab,Instituição Financeira 05,15d2b67e-8971-4cf4-a931-5054cd6fc762,3876,Curso,DEBITO,PAGAMENTO,A_VISTA,ANUIDADE,NaN,NaN,749.80,749.80,BRL,2021-07-29,2021-08-10,NaN,fdf99beb-f235-43f2-a410-d8d279dcfd0f
4,e1711229-cf83-483b-8cc1-0c8d31c81f80,362.529.240-03,63d929c5-2a09-479e-806c-8cd073a029ab,Instituição Financeira 05,371fef19-9345-4fc3-82c5-d5ca910d2ceb,3876,Faculdade,DEBITO,PAGAMENTO,A_VISTA,ANUIDADE,NaN,NaN,1740.57,1740.57,BRL,2021-07-18,2021-08-10,NaN,fdf99beb-f235-43f2-a410-d8d279dcfd0f

## Analisando Tabela Customer

In [46]:
financial_relation =pd.read_json('base_dados/customers/01-financial-relation.json')
personal_identification = pd.read_json('base_dados/customers/01-personal-identification.json')
personal_qualification = pd.read_json('base_dados/customers/01-personal-qualification.json')

In [47]:
financial_relation.to_csv('financial_relation.csv',sep = ';', index=False)
personal_identification.to_csv('personal_identification.csv',sep = ';', index=False)
personal_qualification.to_csv('personal_qualification.csv',sep = ';', index=False)

In [48]:
personal_identification.head()

,personalId,organizationId,customerId,brandName,civilName,socialName,birthDate,maritalStatusCode,sex,companyCnpj,documents,otherDocuments,hasBrazilianNationality,nationality,filiation,contacts
0,4478301e-21e7-49e5-b4a8-bb033f41dab1,63d929c5-2a09-479e-806c-8cd073a029ab,362.529.240-03,Instituição Financeira 05,Cliente 00201,Cliente 00201,2021-05-21,SEPARADO_JUDICIALMENTE,MASCULINO,[00.017.498/7700-72],"{'cpfNumber': '362.529.240-03', 'passportNumbe...",NaN,False,[{'otherNationalitiesInfo': 'BRA'}],NaN,"{'postalAddresses': [{'isMain': True, 'address..."
1,68261048-09eb-4547-bfe5-eac4195aee9b,d3d2b0d5-903a-4f9f-b793-c139490d5ca7,793.879.991-03,Instituição Financeira 09,Cliente 00202,Cliente 00202,2021-05-21,UNIAO_ESTAVEL,MASCULINO,[00.009.921/6370-51],"{'cpfNumber': '793.879.991-03', 'passportNumbe...",NaN,False,[{'otherNationalitiesInfo': 'BRA'}],NaN,"{'postalAddresses': [{'isMain': True, 'address..."
2,a991cd22-8bf8-4ec7-8d0f-7830902a4dd9,69665991-da55-4aac-a1f2-32d23daba8fe,927.518.283-33,Instituição Financeira 03,Cliente 00203,Cliente 00203,2021-05-21,VIUVO,FEMININO,[00.047.912/7906-49],"{'cpfNumber': '927.518.283-33', 'passportNumbe...",NaN,False,[{'otherNationalitiesInfo': 'BRA'}],NaN,"{'postalAddresses': [{'isMain': True, 'address..."
3,2a736423-2fab-4cea-ad5f-f8cb980e03d8,f4851ca0-7163-4d71-97a7-df1e999c047f,181.742.477-09,Instituição Financeira 07,Cliente 00204,Cliente 00204,2021-05-21,SOLTEIRO,MASCULINO,[00.026.814/6240-28],"{'cpfNumber': '181.742.477-09', 'passportNumbe...",NaN,False,[{'otherNationalitiesInfo': 'BRA'}],NaN,"{'postalAddresses': [{'isMain': True, 'address..."
4,aa79da2e-4cea-4dd2-8ab3-28efc63f0117,63d929c5-2a09-479e-806c-8cd073a029ab,233.845.513-06,Instituição Financeira 05,Cliente 00205,Cliente 00205,2021-05-21,OUTRO,OUTRO,[00.017.498/7700-72],"{'cpfNumber': '233.845.513-06', 'passportNumbe...",NaN,False,[{'otherNationalitiesInfo': 'BRA'}],NaN,"{'postalAddresses': [{'isMain': True, 'address..."